name: CI

on:
  push:
    branches: [master]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [master]
    paths-ignore:
      - "**.md"

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
    runs-on: ${{ matrix.os }}-latest

    steps:
      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2

      - name: Check if code is formatted
        run: |
          v fmt -verify . || v fmt -diff .

      - name: linux and mac specifics
        if: startsWith(matrix.os,'ubuntu') || startsWith(matrix.os,'macos')
        run: |
          mkdir -p ~/.vmodules
          cd sgldraw
          ln -s $(pwd) ~/.vmodules/
          ls -al ~/.vmodules/

      - name: windows specifics
        if: startsWith(matrix.os,'windows')
        run: |
          copy-item -force sgldraw $home\.vmodules\

      - name: Build ${{ github.event.repository.name }}
        run: v examples
